# `dr=2` means updated in the last week
search_engine = "https://kagi.com/search?dr=2&q="

search_domains = [
  "applytojob.com/apply/",
  "breezy.hr",
  "icims.com",
  "inflightcloud.com",
  "job-boards.greenhouse.io",
  "jobs.ashbyhq.com",
  "jobs.jobvite.com",
  "jobs.lever.co",
  "jobs.smartrecruiters.com",
  "myworkdayjobs.com",
  "remote.com",
  "remote.io",
  "remotejobs.com/job/",
  "weworkremotely.com/remote-jobs/",
  "ziprecruiter.com/c/",
]

job_roles = [
  "cloud engineer",
  "cybersecurity",
  "developer productivity",
  "devex",
  "devops",
  "devprod",
  "devsecops",
  "infrastructure engineer",
  "observability",
  "platform engineer",
  "site reliability engineer",
  "software engineer",
  "sre",
  "tools engineer",
]

excluded_keywords = ["clearance", "dod", "expired", "intern", "sales"]
